### ISSUE TITLE
It would be nice to clarify the [Deprecated] tag

### ISSUE THREAD

**Issue by 10Dev** [kagawagao/react-grid#76]
It would be nice to clarify the [Deprecated] tag

Your project is listed in the Awesome Ant Design page. It would be nice if you placed a link to the project which has replaced this one or else describe what you mean by [Deprecated]

**Comment by kagawagao** [comment]
I am sorry about this, I'll mark this package as deprecated in npm registry.
Thanks for reminding me !!! 👍

**Comment by kagawagao** [comment]
I opened an [issue](https://github.com/websemantics/awesome-ant-design/issues/2)
